language: generic 
sudo: required
services:
  - docker


before_instal:
  - docker build -t victoraldir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true victoraldir/docker-react npm run test -- --coverage